### ISSUE TITLE
develop branch is outdated

### ISSUE THREAD

**Issue by fuse314** [mauruskuehne/jira-extensions#20]
Do we still need the branch `develop`?
We should be able to branch from `master` and create the pull requests there.

**Comment by fuse314** [comment]
@mauruskuehne @Quarkonaut bump...

**Comment by mauruskuehne** [comment]
@fuse314 hab develop mal als default-branch markiert, develop ist aktuell aber noch einige commits voraus? brauchts da noch einen merge? 🤨

**Comment by fuse314** [comment]
@mauruskuehne du hast "master" als default-branch markiert (korrekt).
Der develop-branch ist 12 commits hinterher und kann jetzt gelöscht werden.
...ausser du hättest noch lokale Änderungen?
