### ISSUE TITLE
Develop Branch

### ISSUE THREAD

**Issue by Quarkonaut** [mauruskuehne/jira-extensions#3]
A `develop` branch should be created from the current `master`branch. Direct commits to `master` should not be allowed after the `develop` branch has been created.
Features and fixes can then be tested on `develop` before they are release to the `master`branch.

**Comment by Quarkonaut** [comment]
@mauruskuehne Created the `develop` branch. As i am not allowed to protect `master`, it is up to you. ;)

**Comment by mauruskuehne** [comment]
branch created, master and develop are now protected
