### ISSUE TITLE
Create PV Document Link for is-e+

### ISSUE THREAD

**Issue by mauruskuehne** [mauruskuehne/jira-extensions#5]
Add an isag:// link that directly inserts a new PV document in is-e+
The link should populate the fields "Bezeichnung" and "Typ".
The document name should be "PV ISSUE-NR"

**Comment by fuse314** [comment]
Document name should be "ISSUE-NR PV"

**Comment by fuse314** [comment]
Issue obsolete.
=> use new feature "test" in jira.
