### ISSUE TITLE
Extend Copy Commit Header Button

### ISSUE THREAD

**Issue by Quarkonaut** [mauruskuehne/jira-extensions#6]
Currently, the the commit message header can be copied to the clipboard by means of the _Copy Commit Header_ Button. For other use-cases (Documents, personal Time-Sheets etc.) other user-defined formats would be useful.

# Details
## Configuration
A Configuration page for the script shall be implemented. The user may configure up to 5 custom formats. Custom formats may contain one or two format strings. One format string targets tasks without a parent task, the other format string targets tasks with a parent task.

The following placeholders may be specified.

Placeholder | Description
--- | ---
%ID% | Identifier of the current Task.
%TITLE% | Title of the current Task.
%P_ID% | Identifier of the parent Task.
%P_TITLE% | Title of the parent Task.
\n | New Line
\t | Tab
## Behavior
If no custom formats are configured, the behavior of the _Copy Commit Header_ Button remains as it is. If one or more custom formats are configured, the Button is re-labeled as _Copy Task Header_ and acts as a drop-down Button. The first item of the drop-down must always be the _Copy Commit Header_ action, the other items represent actions to copy the user configured formats. Formats targeting parent tasks must only be available if the current task has a parent.

**Comment by fuse314** [comment]
@Quarkonaut most of these things are "configurable" manually: Additional / different buttons can be configured by means of ``GM_setValue("extraButtons" ...`` [(see example in script)](https://github.com/mauruskuehne/jira-extensions/blob/5aa89c9faa2dd77ece89211e4e516fa52b43ab35/jira-innosolv-ch.user.js#L34)

Visual configuration of these buttons with a dialog will be very complex and will probably not be implemented 😢.

Should we keep this issue open anyway?

**Comment by Quarkonaut** [comment]
We can close this.
